# Generated by Django 3.2.13 on 2023-06-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VerticalSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('subagent', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('oem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerapp.oem')),
                ('tags', models.ManyToManyField(to='partnerapp.Tag')),
                ('vertical_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerapp.verticalsector')),
            ],
        ),
    ]
