# Generated by Django 3.2.13 on 2023-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='vertical_sector',
        ),
        migrations.AddField(
            model_name='partner',
            name='vertical_sectors',
            field=models.ManyToManyField(to='partnerapp.VerticalSector'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
