# Generated by Django 3.2.13 on 2023-06-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0002_auto_20230601_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='company_name',
            new_name='primary_partner',
        ),
    ]
