# Generated by Django 3.2.13 on 2023-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0003_rename_company_name_partner_primary_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='oem',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='OEM',
        ),
    ]
