# Generated by Django 3.2.13 on 2023-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0004_auto_20230601_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='product',
            new_name='solution',
        ),
        migrations.AddField(
            model_name='partner',
            name='use_case',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
