# Generated by Django 4.2.1 on 2023-06-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0006_auto_20230601_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='primary_partner',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='subagents',
        ),
        migrations.RemoveField(
            model_name='partnersubagent',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnersubagent',
            name='subagent',
        ),
        migrations.RemoveField(
            model_name='solutionassociation',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solutionassociation',
            name='subagent',
        ),
        migrations.RemoveField(
            model_name='solutionassociation',
            name='use_case',
        ),
        migrations.RemoveField(
            model_name='oem',
            name='associations',
        ),
        migrations.RemoveField(
            model_name='primarypartner',
            name='vertical_sectors',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='associations',
        ),
        migrations.AddField(
            model_name='primarypartner',
            name='sub_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerapp.subagent'),
        ),
        migrations.AddField(
            model_name='solution',
            name='oems',
            field=models.ManyToManyField(help_text='Specify one or many OEMs for this solution', to='partnerapp.oem'),
        ),
        migrations.AddField(
            model_name='solution',
            name='use_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerapp.usecase'),
        ),
        migrations.AddField(
            model_name='solution',
            name='verticals',
            field=models.ManyToManyField(help_text='Specify one or many Verticals for this solution', to='partnerapp.verticalsector'),
        ),
        migrations.AlterField(
            model_name='primarypartner',
            name='name',
            field=models.CharField(help_text='Enter the primary partner name', max_length=100),
        ),
        migrations.AlterField(
            model_name='subagent',
            name='primary_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerapp.primarypartner'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='subagent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerapp.subagent'),
        ),
        migrations.AlterField(
            model_name='verticalsector',
            name='name',
            field=models.CharField(choices=[('Transportation & Logistics', 'Transportation & Logistics'), ('Police/Fire', 'Police/Fire'), ('K-12', 'K-12'), ('Higher Ed', 'Higher Ed'), ('Financial Services', 'Financial Services'), ('Municipalities', 'Municipalities'), ('Retail', 'Retail'), ('Tech, Media, & Services', 'Tech, Media, & Services'), ('Logistics', 'Logistics'), ('Oil, Gas & Utility', 'Oil, Gas & Utility'), ('Healthcare', 'Healthcare')], help_text='Vertical Sector', max_length=100),
        ),
        migrations.DeleteModel(
            name='OEMAssociation',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PartnerSubagent',
        ),
        migrations.DeleteModel(
            name='SolutionAssociation',
        ),
    ]
