# Generated by Django 4.0.10 on 2023-06-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0007_remove_partner_primary_partner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarypartner',
            name='sub_agent',
        ),
    ]
