# Generated by Django 4.0.10 on 2023-06-05 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0008_remove_primarypartner_sub_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='oems',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='use_case',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='verticals',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='subagent',
        ),
        migrations.CreateModel(
            name='Subagent_Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oems', models.ManyToManyField(help_text='Specify one or many OEMs for this solution', to='partnerapp.oem')),
                ('subagent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerapp.subagent')),
                ('use_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerapp.usecase')),
                ('verticals', models.ManyToManyField(help_text='Specify one or many Verticals for this solution', to='partnerapp.verticalsector')),
            ],
        ),
    ]
