# Generated by Django 4.0.10 on 2023-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0010_subagent_association_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagent_association',
            name='name',
            field=models.TextField(default='None for None from None'),
        ),
    ]
