# Generated by Django 4.0.10 on 2023-06-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0015_subagent_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subagent_association',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
