# Generated by Django 4.0.10 on 2023-06-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0016_alter_subagent_association_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subagent_association',
            name='name',
        ),
    ]
