# Generated by Django 4.0.10 on 2023-06-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0017_remove_subagent_association_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subagent_Association',
        ),
    ]
