# Generated by Django 4.0.10 on 2023-06-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0019_subagent_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagent_association',
            name='name',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
