# Generated by Django 4.0.10 on 2023-06-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0021_product_association_delete_subagent_association'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Association',
            new_name='ProductAssociation',
        ),
    ]
